name: Publish Artifact

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: if [ -f "requirements.txt" ]; then pip install -r requirements.txt else echo "No requirements.txt yet."

    - name: Generate requirements
      run: pip freeze > requirements.txt

    - name: Install pyinstaller
      run: pip install pyinstaller

    - name: Create Executable
      run: pyinstaller --onefile main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Message_Sender
        path: .\dist\main.exe

    - name: Upload requirements.txt
      uses: actions/upload-artifact@v2
      with:
        name: requirements
        path: requirements.txt
      
